<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Replay</AssemblyName>
    <RootNamespace>Replay.Mobile</RootNamespace>
    <Version>1.5.2</Version>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Optimize>true</Optimize>
    <DebugType>embedded</DebugType>
    <Deterministic>true</Deterministic>
    <StarryReferences Condition="'$(StarryReferences)' == ''">../References</StarryReferences>
    <StarryAnalyzer Condition="'$(StarryAnalyzer)' == ''">$(StarryReferences)/StArray.ModManager.Analyzer.dll</StarryAnalyzer>
  </PropertyGroup>

  <ItemGroup>
    <Analyzer Include="$(StarryAnalyzer)" />
    <Reference Include="StArray.ModManager">
      <HintPath>$(StarryReferences)/StArray.ModManager.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="StArray.ModManager.Android">
      <HintPath>$(StarryReferences)/StArray.ModManager.Android.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ImGui.NET">
      <HintPath>$(StarryReferences)/ImGui.NET.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System.Formats.Nrbf">
      <HintPath>$(StarryReferences)/System.Formats.Nrbf.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
